version: '3'
services:
  hero-picker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis
      - prometheus
      - grafana
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 10
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Reference the local prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
        - ./grafana:/var/lib/grafana
        - ./datasources:/etc/grafana/provisioning/datasources