app:
  port: "8081"
redis:
  address: "localhost:6379"
  password:
  name: 0
  timeout: 100000000000000
dataset:
  path: "./internal/pkg/repository/dataset/dataset.csv"
client:
  timeout: 50000000000000
  retries: 4
  base_path: "https://api.opendota.com/api/benchmarks"