global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hero-picker'
    static_configs:
      - targets: ['hero-picker:8081']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
