name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create cmd/myapp Directory
        run: mkdir -p cmd/myapp

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Choose your Go version

      - name: Run Tests
        run: go test ./...

      - name: Build Application
        run: go build ./...

      - name: Deploy to Production
        if: success()
        run: |
          # Add your deployment script or commands here
